apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::711039118774:role/github-actions-eks
      username: github-actions
      groups:
        - system:masters
