name: Deploy to EKS (Helm only)

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  HELM_RELEASE: nextjs
  HELM_CHART_PATH: .ops/helm
  K8S_NAMESPACE: test-deploy

jobs:
  deploy:
    runs-on: demo-runners-dmnl5-runner-smrqp


    steps:
      # ------------------------------------------------------------
      # Checkout code 1
      # ------------------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ------------------------------------------------------------
      # Verify Kubernetes access (ARC runner already authenticated)
      # ------------------------------------------------------------
      - name: Verify cluster access
        run: |
          kubectl get nodes
          kubectl get ns

      # ------------------------------------------------------------
      # Deploy with Helm
      # ------------------------------------------------------------
      - name: Deploy with Helm
        run: |
          helm upgrade --install "$HELM_RELEASE" "$HELM_CHART_PATH" \
            --namespace "$K8S_NAMESPACE" \
            --create-namespace \
            --atomic \
            --timeout 5m
